<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AirlyPilot</AssemblyName>
    <RootNamespace>AirlyATC</RootNamespace>
    <ApplicationIcon>Airly.ico</ApplicationIcon>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
</Project>